[[main]]
  name = "Kursus"
  weight = 10
  identifier = "kursus"
  url = "/docs/introduktion/kursus-introduktion/"

[[main]]
  name = "Kursus Introduktion"
  weight = 10
  identifier = "introduktion"
  url = "/docs/introduktion/kursus-introduktion/"
  parent = "kursus"

[[main]]
  name = "Excel Introduktion"
  weight = 20
  identifier = "excel"
  url = "/docs/excel/excel-introduktion/"
  parent = "kursus"

[[main]]
  name = "Excel"
  weight = 10
  identifier = "excel"
  url = "/docs/excel/excel/"
  parent = "excel"

[[main]]
  name = "Pivottabel"
  weight = 20
  identifier = "excel"
  url = "/docs/excel/pivottabel/"
  parent = "excel"

[[main]]
  name = "Project"
  weight = 30
  identifier = "project"
  url = "/docs/project/project-introduktion/"
  parent = "kursus"

  [[main]]
  name = "Data"
  weight = 40
  identifier = "data"
  url = "/docs/database/database-introduktion/"
  parent = "kursus"

    [[main]]
  name = "SQL"
  weight = 10
  identifier = "sql"
  url = "/docs/database/database-introduktion/"
  parent = "data"

  [[main]]
  name = "Excel Office Script"
  weight = 50
  identifier = "officescript"
  url = "/docs/officescript/officescript-introduktion/"
  parent = "kursus"