[[main]]
  name = "Kursus"
  weight = 10
  identifier = "kursus"
  url = "/docs/introduktion/kursus-introduktion/"

[[main]]
  name = "Kursus Introduktion"
  weight = 10
  identifier = "introduktion"
  url = "/docs/introduktion/kursus-introduktion/"
  parent = "kursus"

[[main]]
  name = "Excel"
  weight = 20
  identifier = "excel"
  url = "/docs/excel/excel-introduktion/"
  parent = "kursus"

[[main]]
  name = "Project"
  weight = 30
  identifier = "project"
  url = "/docs/project/project-introduktion/"
  parent = "kursus"
