[[main]]
  name = "Kursus"
  weight = 10
  identifier = "kursus"
  url = "/docs/introduktion/"

[[main]]
  name = "Kursus Introduktion"
  weight = 10
  identifier = "kursusintro"
  url = "/docs/introduktion/"
  parent = "kursus"

[[main]]
  name = "Excel"
  weight = 20
  identifier = "excel"
  url = "/docs/excel/"
  parent = "kursus"

[[main]]
  name = "Project"
  weight = 30
  identifier = "project"
  url = "/docs/project/"
  parent = "kursus"

  [[main]]
  name = "Data"
  weight = 40
  identifier = "data"
  url = "/docs/database/"
  parent = "kursus"

  [[main]]
  name = "Excel Office Script"
  weight = 50
  identifier = "officescript"
  url = "/docs/officescript/"
  parent = "kursus"

  [[main]]
  name = "Power"
  weight = 60
  identifier = "power"
  url = "/docs/power/"
  parent = "kursus"

  [[main]]
  name = "VBA"
  weight = 60
  identifier = "vba"
  url = "/docs/vba/"
  parent = "kursus"